title: Voyager
description: Next Generation 3D Editing and Viewing Tool Suite

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

#color_scheme: "dark"
search_enabled: false

aux_links:
  "Voyager on Github":
    - "//github.com/Smithsonian/dpo-voyager"